1) Cтворіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [19]:
import numpy as np

v = np.arange(1, 11)
print(v)

[ 1  2  3  4  5  6  7  8  9 10]


2) Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [20]:
import numpy as np

m = np.zeros((3,3), dtype = int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3) Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [21]:
import numpy as np

m = np.random.randint(1, 11, size=(5, 5))
print(m)

[[ 3 10  2  3  8]
 [ 3  3  6  2  4]
 [ 6  3  2  3  2]
 [ 5  6  9 10 10]
 [10 10 10  9  5]]


4) Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [22]:
import numpy as np

m = np.random.random((4, 4))
print(m)

[[0.59582154 0.59358148 0.64074491 0.53748283]
 [0.85644465 0.0213051  0.73558939 0.33439547]
 [0.17353135 0.5957181  0.44022877 0.24633427]
 [0.44771462 0.05242959 0.77300223 0.79969566]]


5) Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні 
операції додавання, віднімання та множення.

In [23]:
import numpy as np

v1 = np.random.randint(1, 10, size=5)
v2 = np.random.randint(1, 10, size=5)
print(v1 + v2)
print(v1 - v2)
print(v1 * v2)

[ 3  5 10 13  6]
[-1 -3 -6  3  0]
[ 2  4 16 40  9]


6) Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [24]:
import numpy as np

v1 = np.random.random(7)
v2 = np.random.random(7)
print(np.dot(v1, v2))

0.8685225476857557


7) Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [25]:
import numpy as np 

m1 = np.random.randint(1, 10, size=(2, 2)) 
m2 = np.random.randint(1, 10, size=(2, 3)) 
print(np.dot(m1, m2))

[[ 54 109  88]
 [ 31  39  28]]


8) Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [26]:
import numpy as np

m1 = np.random.randint(1, 10, size=(3, 3))
print(np.linalg.inv(m1))

[[ 0.06382979  0.14893617 -0.10638298]
 [-0.14893617  0.31914894 -0.08510638]
 [ 0.57446809 -1.65957447  1.04255319]]


9) Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.


In [27]:
import numpy as np

m = np.random.random((4, 4))
print(m.T)

[[0.40883465 0.86520329 0.81353984 0.01508129]
 [0.38864717 0.0337767  0.97763768 0.82521558]
 [0.00870079 0.82187515 0.29389486 0.23288516]
 [0.73361675 0.43532249 0.31239935 0.090974  ]]


10) Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на 
вектор.

In [28]:
import numpy as np

m = np.random.randint(1, 10, size=(3, 4))
v = np.random.randint(1, 10, size=4)
print(np.dot(m, v))

[ 77  62 120]


11) Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте 
матрицю на вектор.

In [29]:
import numpy as np

m = np.random.random((2, 3))
v = np.random.random(3)
print(np.dot(m, v))

[0.73659113 0.59792201]


12) Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [30]:
import numpy as np

m1 = np.random.randint(1, 10, size=(2, 2))
m2 = np.random.randint(1, 10, size=(2, 2))
print(m1 * m2)

[[ 2 21]
 [48 32]]


13) Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [31]:
import numpy as np

m1 = np.random.randint(1, 10, size=(2, 2))
m2 = np.random.randint(1, 10, size=(2, 2))
print(np.dot(m1 ,m2))

[[90 96]
 [16 14]]


14) Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [32]:
import numpy as np

m = np.random.randint(1, 100, size=(5, 5))
print(np.sum(m))

1509


15) Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [33]:
import numpy as np

m1 = np.random.randint(1, 10, size=(4, 4))
m2 = np.random.randint(1, 10, size=(4, 4))
print(m1 - m2)

[[ 1  4 -3 -6]
 [ 5 -3  1 -3]
 [ 2 -3 -4  2]
 [ 6  2  1  0]]


16) Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить 
суму елементів кожного рядка матриці.

In [34]:
import numpy as np

m = np.random.random((3, 3))
v_s = np.array([[sum(rows)] for rows in m] )
print(v_s)

[[1.98565678]
 [0.89691777]
 [0.42918768]]


17) Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [35]:
import numpy as np

m = np.random.randint(1, 10, size=(3, 4))
print(m ** 2)

[[ 1 64 36  9]
 [49 16 25 81]
 [81 64  9 16]]


18) Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [36]:
import numpy as np

v = np.random.randint(1, 50, size=4)
print(np.sqrt(v))

[3.31662479 3.60555128 5.38516481 5.91607978]
